yarnPath: .yarn/releases/yarn-4.9.2.cjs
nodeLinker: node-modules

# Performance optimizations
compressionLevel: mixed
enableGlobalCache: false

# Security
enableScripts: false
enableTelemetry: false

# Development experience  
enableColors: true
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
